


###
curl -X POST "https://lzpdqzzobdjaosxydixl.supabase.co/functions/v1/get-barril-info-actual" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{$dotenv SUPABASE_ANON_KEY}}" \
  -d '{"barril_id": "B001"}'


### CASO BARRIL B001 - INFO ACTUAL
curl -X POST "https://lzpdqzzobdjaosxydixl.supabase.co/functions/v1/main-info-barriles" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{$dotenv SUPABASE_ANON_KEY}}" \
  -d '{"tipo": "ACTUAL", "barril_id": "B001"}'
### CASO BARRIL B001 - INFO HISTORICA
curl -X POST "https://lzpdqzzobdjaosxydixl.supabase.co/functions/v1/main-info-barriles" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{$dotenv SUPABASE_ANON_KEY}}" \
  -d '{"tipo": "HISTORICO", "barril_id": "B001"}'
  
### CASO TODOS LOS BARRILES - INFO ACTUAL
curl -X POST "https://lzpdqzzobdjaosxydixl.supabase.co/functions/v1/main-info-barriles" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{$dotenv SUPABASE_ANON_KEY}}" \
  -d '{"tipo": "ACTUAL"}'
### CASO TODOS LOS BARRILES - INFO HISTORICA
curl -X POST "https://lzpdqzzobdjaosxydixl.supabase.co/functions/v1/main-info-barriles" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{$dotenv SUPABASE_ANON_KEY}}" \
  -d '{"tipo": "HISTORICO"}'


###  OBTENER INFO DE BARRILES VACIADOS - FIX LATER !!!!
curl -X POST "https://lzpdqzzobdjaosxydixl.supabase.co/functions/v1/main-info-vaciado" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer {{$dotenv SUPABASE_ANON_KEY}}" \
-d '{
  "barril_id": "B003",
  "evento": "Festival de Cerveza"
}'